version: "3.9"
name: "frelin-bilqis 24c"
services:
  # Service 1: NGINX (Web Server)
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
    networks:
      - app_network

  # Service 2: PostgreSQL (Database)
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Service 3: PGAdmin (Database Management)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app_network

  # Service 4: Redis (Cache)
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network

  # Service 5: Wordpress (CMS)
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: postgres
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: mydatabase
    ports:
      - "8081:80"
    networks:
      - app_network

  # Service 6: MariaDB (Database)
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: anotherdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  # Service 7: RabbitMQ (Message Queue)
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app_network

  # Service 8: Node.js (Web App)
  nodejs:
    image: node:latest
    working_dir: /app
    volumes:
      - ./node_app:/app
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  mariadb_data:
